# Styler Object and Customising the Display
# Formatting the Display
## Formatting Values

In [1]:
import pandas as pd
import numpy as np

df = pd.DataFrame(
    {
        "strings": ["Adam", "Mike"],
        "ints": [1, 3],
        "floats": [1.123, 1000.23],
    }
)

(
    df.style.format(precision=3, thousands=".", decimal=",")
    .format_index(str.upper, axis=1)
    .relabel_index(["row 1", "row 2"], axis=0)
)

Using the formatting functions while still relying on the underlying data for indexing and calculations.

In [2]:
weather_df = pd.DataFrame(
    np.random.default_rng().random((10, 2)) * 5,
    index=pd.date_range(start="2021-01-01", periods=10),
    columns=["Tokyo", "Beijing"],
)


def rain_condition(v):
    if v < 1.75:
        return "Dry"
    elif v < 2.75:
        return "Rain"
    return "Heavy Rain"


def make_pretty(styler: pd.io.formats.style.Styler):
    styler.set_caption("Weather Conditions")
    styler.format(rain_condition)
    styler.format_index(lambda v: v.strftime("%A"))  # extracts the full name of the day of the week
    styler.background_gradient(axis=None, vmin=1, vmax=5, cmap="YlGnBu")

    return styler

In [3]:
weather_df

               Tokyo   Beijing
2021-01-01  4.367875  2.131675
2021-01-02  1.831372  4.223505
2021-01-03  3.141755  3.997238
2021-01-04  3.384421  3.156182
2021-01-05  3.354022  4.627157
2021-01-06  2.243723  4.450306
2021-01-07  3.188155  3.572518
2021-01-08  4.583499  4.887819
2021-01-09  1.819668  2.502425
2021-01-10  2.672868  0.698376

In [4]:
weather_df.loc["2021-01-04":"2021-01-08"].style.pipe(make_pretty)

## Hiding Data

In [5]:
df = pd.DataFrame(np.random.default_rng().standard_normal((5, 5)))
(df.style.hide(subset=[0, 2, 4], axis=0).hide(subset=[0, 2, 4], axis=1))

In [6]:
show = [0, 2, 4]
(
    df.style.hide(
        [row for row in df.index if row not in show],
        axis=0,
    ).hide(
        [col for col in df.columns if col not in show],
        axis=1,
    )
)

## Concatenating DataFrame Outputs

In [7]:
# Independently styling two DataFrames and concatenating them
# Note that the concatenated table preserves the independent styles:
summary_styler = (
    df.agg(
        ["sum", "mean"],
    )
    .style.format(precision=3)
    .relabel_index(["Sum", "Average"])
)
df.style.format(precision=1).concat(summary_styler)

# Styler Object and HTML

In [8]:
idx = pd.Index(["Tumour (Positive)", "Non-Tumour (Negative)"], name="Actual Label:")
cols = pd.MultiIndex.from_product(
    [
        ["Decision Tree", "Regression", "Random"],
        ["Tumour", "Non-Tumour"],
    ],
    names=["Model:", "Predicted"],
)
df = pd.DataFrame(
    [
        [38.0, 2.0, 18.0, 22.0, 21, np.nan],
        [19, 439, 6, 452, 226, 232],
    ],
    index=idx,
    columns=cols,
)
df.style

In [9]:
s = df.style.format("{:.0f}").hide(
    [("Random", "Tumour"), ("Random", "Non-Tumour")],
    axis="columns",
)
s

# Methods to Add Styles

# Table Styles

In [10]:
# For row hover use <tr> instead of <td>
cell_hover = {
    "selector": "td:hover",
    "props": [("background-color", "#FFFFB3"), ("color", "black")],
}
index_names = {
    "selector": ".index_name",
    "props": "font-style: italic; color: darkgrey; font-weight: normal;",
}
headers = {
    "selector": "th:not(.index_name)",
    "props": "background-color: #000066; color: white;",
}

s.set_table_styles([cell_hover, index_names, headers])

In [11]:
# Preserve the previous styles we have set, by specifying overwrite=False
s.set_table_styles(
    [
        {"selector": "th.col_heading", "props": "text-align: center;"},
        {"selector": "th.col_heading.level0", "props": "font-size: 1.5em;"},
        {"selector": "td", "props": "text-align: center; font-weight: bold"},
    ],
    overwrite=False,
)

In [12]:
# We can also pass in a dict with row or column keys
s.set_table_styles(
    {
        ("Regression", "Tumour"): [
            {"selector": "th", "props": "border-left: 1px solid white"},
            {"selector": "td", "props": "border-left:1px solid #000066"},
        ]
    },
    overwrite=False,
    axis=0,
)

# Setting Classes and Linking to External CSS

## Table Attributes

In [13]:
# Add a class to the main <table>
out = s.set_table_attributes("class='my-table-cls'").to_html()
print(out[out.find("<table") :][:109])

<table id="T_29c97" class='my-table-cls'>
  <thead>
    <tr>
      <th class="index_name level0" >Model:</th>

## Data Cell CSS Classes

In [14]:
# Create our own CSS classes internally and add them to table style
s.set_table_styles(
    [
        # create internal CSS classes
        {"selector": ".true", "props": "background-color: #E6FFE6;"},
        {"selector": ".false", "props": "background-color: #FFE6E6;"},
    ],
    overwrite=False,
)
cell_color = pd.DataFrame(
    [
        ["true ", "false ", "true ", "false "],
        ["false ", "true ", "false ", "true "],
    ],
    index=df.index,
    columns=df.columns[:4],
)

s.set_td_classes(cell_color)

# Styler Functions
## Acting on Data

In [15]:
df2 = pd.DataFrame(
    np.random.default_rng(0).standard_normal((10, 4)),
    columns=list("ABCD"),
)
df2.style

In [16]:
def style_negative(v, props=""):
    """Colors text red, if it's negative"""
    return props if v < 0 else None


s2 = df2.style.map(
    style_negative,
    props="color: red;",
).map(
    lambda v: "opacity: 20%;" if (v < 0.3) and (v > -0.3) else None,
)
s2

In [17]:
def highlight_max(s, props=""):
    """Highlight the maximum value in a column"""
    return np.where(s == np.nanmax(s.values), props, "")


s2.apply(highlight_max, props="color:white; background-color: darkblue;", axis=0)

In [18]:
# Highlight the DataFrame maximum in purple
# Highlight row maximums in pink
s2.apply(highlight_max, props="color: white;background-color: pink;", axis=1).apply(
    highlight_max, props="color: white;background-color: purple", axis=None
)

## Acting on the Index and Column Headers

In [19]:
s2.map_index(lambda v: "color: pink;" if v > 4 else "color: darkblue;", axis=0)
s2.apply_index(lambda s: np.where(s.isin(["A", "B"]), "color: pink;", "color: darkblue;"), axis=1)

# Tooltips and Captions

In [20]:
s.set_caption(
    "Confusion matrix for multiple cancer prediction models.",
).set_table_styles(
    [
        {
            "selector": "caption",
            "props": "caption-side: bottom; font-size: 1.25em;",
        }
    ],
    overwrite=False,
)

In [21]:
tt = pd.DataFrame(
    [
        [
            "This model has a very strong true positive rate (TP)",
            "This model's total number of false negatives is too high (FN)",
        ]
    ],
    index=["Tumour (Positive)"],
    columns=df.columns[[0, 3]],
)
s.set_tooltips(
    tt,
    props="visibility: hidden; position: absolute; z-index: 1; "
    "border: 1px solid #000066;"
    "background-color: white; color: #000066; font-size: 0.8em;"
    "transform: translate(0px,-24px); padding: 0.6em;"
    "border-radius: 0.5em;",
)

In [22]:
s.set_table_styles(
    [  # create internal CSS classes
        {"selector": ".border-red", "props": "border: 2px dashed red;"},
        {"selector": ".border-green", "props": "border: 2px dashed green;"},
    ],
    overwrite=False,
)
cell_border = pd.DataFrame(
    [
        ["border-green ", " ", " ", "border-red "],
        [" ", " ", " ", " "],
    ],
    index=df.index,
    columns=df.columns[:4],
)
s.set_td_classes(cell_color + cell_border)

# Finer Control with Slicing

In [23]:
df3 = pd.DataFrame(
    np.random.default_rng().standard_normal((4, 4)),
    pd.MultiIndex.from_product([["A", "B"], ["r1", "r2"]]),
    columns=["c1", "c2", "c3", "c4"],
)
df3

            c1        c2        c3        c4
A r1 -0.071258  0.099254 -0.756548 -1.952248
  r2  0.246480  1.461404 -0.573124  1.054066
B r1 -1.208920 -1.228511 -1.532927 -1.442870
  r2 -1.278784 -0.378404  0.610278  1.839265

In [24]:
# Highlight maximums in third and fourth columns
# Highlight sliced region in yellow
slice_ = ["c3", "c4"]
df3.style.apply(highlight_max, props="color: red;", axis=0, subset=slice_).set_properties(
    **{"background-color": "#FFFFB3"}, subset=slice_
)

In [25]:
# Index across both dimensions
# Take all labels from level 0 and only label "r1" from level 1;
# Then take only columns c2, c3 and c4
idx = pd.IndexSlice
slice_ = idx[idx[:, "r1"], idx["c2":"c4"]]

df3.style.apply(
    highlight_max,
    props="color: red;",
    axis=0,
    subset=slice_,
).set_properties(
    **{"background-color": "#FFFFB3"},
    subset=slice_,
)

In [26]:
slice_ = idx[idx[:, "r2"], :]
df3.style.apply(
    highlight_max,
    props="color: red;",
    axis=1,
    subset=slice_,
).set_properties(**{"background-color": "#FFFFB3"}, subset=slice_)

In [27]:
# Highlight maximum across columns 2 and 4 BUT only if the
# sum of columns 1 and 2 is less than -2.0
slice_ = idx[idx[(df3["c1"] + df3["c3"]) < -2.0], ["c2", "c4"]]
df3.style.apply(
    highlight_max,
    props="color: red;",
    axis=1,
    subset=slice_,
).set_properties(
    **{"background-color": "#FFFFB3"},
    subset=slice_,
)

# Optimization

## 1. Remove UUID and cell_ids

In [28]:
from pandas.io.formats.style import Styler

df4 = pd.DataFrame([[1, 2], [3, 4]])
s4 = Styler(df4, uuid_len=0, cell_ids=False)

## 2. Use Table Styles

In [29]:
props = "font-family: 'Times New Roman', Times, serif; color: #E83E8C; font-size: 1.3em;"
df4.style.set_table_styles([{"selector": "td.col1", "props": props}])

## 3. Set Classes Instead of Using Styler Functions

In [30]:
build = lambda x: pd.DataFrame(x, index=df2.index, columns=df2.columns)
cls1 = build(df2.apply(highlight_max, props="cls-1 ", axis=0))
cls2 = build(df2.apply(highlight_max, props="cls-2 ", axis=1, result_type="expand").values)
cls3 = build(highlight_max(df2, props="cls-3 "))
df2.style.set_table_styles(
    [
        {"selector": ".cls-1", "props": "color:white;background-color:darkblue;"},
        {"selector": ".cls-2", "props": "color:white;background-color:pink;"},
        {"selector": ".cls-3", "props": "color:white;background-color:purple;"},
    ]
).set_td_classes(cls1 + cls2 + cls3)

## 4. Don't Use Tooltips
## 5. If every byte counts, use string replacement

In [31]:
my_css = {
    "row_heading": "",
    "col_heading": "",
    "index_name": "",
    "col": "c",
    "row": "r",
    "col_trim": "",
    "row_trim": "",
    "level": "l",
    "data": "",
    "blank": "",
}
html = Styler(df4, uuid_len=0, cell_ids=False)
html.set_table_styles(
    [
        {"selector": "td", "props": props},
        {"selector": ".c1", "props": "color:green;"},
        {"selector": ".l0", "props": "color:blue;"},
    ],
    css_class_names=my_css,
)
print(html.to_html())

<style type="text/css">
#T_ td {
  font-family: 'Times New Roman', Times, serif;
  color: #E83E8C;
  font-size: 1.3em;
}
#T_ .c1 {
  color: green;
}
#T_ .l0 {
  color: blue;
}
</style>
<table id="T_">
  <thead>
    <tr>
      <th class=" l0" >&nbsp;</th>
      <th class=" l0 c0" >0</th>
      <th class=" l0 c1" >1</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th class=" l0 r0" >0</th>
      <td class=" r0 c0" >1</td>
      <td class=" r0 c1" >2</td>
    </tr>
    <tr>
      <th class=" l0 r1" >1</th>
      <td class=" r1 c0" >3</td>
      <td class=" r1 c1" >4</td>
    </tr>
  </tbody>
</table>

In [32]:
html

# Builtin Styles

## Highlight Null

In [33]:
df2.iloc[0, 2] = np.nan
df2.iloc[4, 3] = np.nan
df2.loc[:4].style.highlight_null(color="#BA2C1F")

## Highlight Min or Max

In [34]:
df2.loc[:4].style.highlight_max(
    axis=1,
    props=("color: white; font-weight: bold; background: darkblue;"),
)

## Highlight Between

In [35]:
left = pd.Series([1.0, 0.0, 1.0], index=["A", "B", "D"])
df2.loc[:4].style.highlight_between(
    left=left,
    right=1.5,
    axis=1,
    props="color: white; background:purple;",
)

## Highlight Quantile

In [36]:
df2.loc[:4].style.highlight_quantile(q_left=0.85, axis=None, color="yellow")

## Background Gradient and Text Gradient

In [37]:
import seaborn as sns

cm = sns.light_palette("green", as_cmap=True)
df2.style.background_gradient(cmap=cm)

In [38]:
df2.style.text_gradient(cmap=cm)

## Set Properties

In [39]:
df2.loc[:4].style.set_properties(
    **{
        "background": "black",
        "color": "lawngreen",
        "border-color": "white",
    }
)

## Bar Charts

In [40]:
df2.style.bar(subset=["A", "B"], color="#D65F5F")

In [41]:
df2.style.format("{:.3f}", na_rep="").bar(
    align=0,
    vmin=-2.5,
    vmax=2.5,
    cmap="bwr",
    height=50,
    width=60,
    props="width: 120px; border-right: 1px solid black;",
).text_gradient(
    cmap="bwr",
    vmin=-2.5,
    vmax=2.5,
)

# Sharing Styles

In [42]:
# The style we want to export
style1 = (
    df2.style.map(style_negative, props="color: red;")
    .map(lambda v: "opacity: 20%;" if (v < 0.3) and (v > -0.3) else None)
    .set_table_styles([{"selector": "th", "props": "color: blue;"}])
    .hide(axis="index")
)

style1

In [43]:
style2 = df3.style
style2.use(style1.export())

style2

# Limitations

# Other Fun and Useful Stuff
## Widgets

In [46]:
from ipywidgets import widgets


@widgets.interact
def f(h_neg=(0, 359, 1), h_pos=(0, 359), s=(0.0, 99.9), l_post=(0.0, 99.9)):
    return df2.style.background_gradient(
        cmap=sns.palettes.diverging_palette(h_neg=h_neg, h_pos=h_pos, s=s, l=l_post, as_cmap=True)
    )

interactive(children=(IntSlider(value=179, description='h_neg', max=359), IntSlider(value=179, description='h_…

## Magnify

In [51]:
def magnify():
    return [
        {"selector": "th", "props": [("font-size", "4pt")]},
        {"selector": "td", "props": [("padding", "0em 0em")]},
        {"selector": "th:hover", "props": [("font-size", "12pt")]},
        {"selector": "tr:hover td:hover", "props": [("max-width", "200px"), ("font-size", "12pt")]},
    ]

In [52]:
cmap = sns.diverging_palette(5, 250, as_cmap=True)
bigdf = pd.DataFrame(np.random.default_rng(25).standard_normal((20, 25))).cumsum()
bigdf.style.background_gradient(cmap, axis=1).set_properties(**{"max-width": "80px", "font-size": "1pt"}).set_caption(
    "Hover to magnify"
).format(precision=2).set_table_styles(magnify())

## Sticky Headers

In [53]:
bigdf = pd.DataFrame(np.random.default_rng().standard_normal((16, 100)))
bigdf.style.set_sticky(axis="index")

## HTML Escaping

In [56]:
df4 = pd.DataFrame([["<div></div>", "'&other'", "<span></span>"]])
df4.style

In [57]:
df4.style.format(escape="html")

In [58]:
df4.style.format("<a href='https://pandas.pydata.org' target='_blank'>{}</a>", escape="html")

## Export to Excel

In [ ]:
df2.style.map(
    style_negative,
    props="color: red;",
).highlight_max(axis=0).to_excel(
    "styled.xlsx",
    engine="openpyxl",
)