Set or get options directly as attributes of the top-level `options` attribute:

In [28]:
import pandas as pd
import numpy as np

pd.options.display.max_rows

7

In [29]:
pd.options.display.max_rows = 999
pd.options.display.max_rows

999

In [30]:
# Query the current value of a given option in the pandas configuration system.
pd.get_option("display.chop_threshold")

4

In [31]:
pd.set_option("display.chop_threshold", 2)

In [32]:
pd.get_option("display.chop_threshold")

2

In [33]:
# Notice how we use a regex for the option
pd.set_option("chop", 4)

In [34]:
pd.get_option("display.chop_threshold")

4

In [35]:
# This regex doesn't work. It matches multiple option names.
pd.get_option("max")

OptionError: 'Pattern matched multiple keys'

# Available Options

In [36]:
pd.describe_option()

compute.use_bottleneck : bool
    Use the bottleneck library to accelerate if it is installed,
    the default is True
    Valid values: False,True
    [default: True] [currently: True]
compute.use_numba : bool
    Use the numba engine option for select operations if it is installed,
    the default is False
    Valid values: False,True
    [default: False] [currently: False]
compute.use_numexpr : bool
    Use the numexpr library to accelerate computation if it is installed,
    the default is True
    Valid values: False,True
    [default: True] [currently: True]
display.chop_threshold : float or None
    if set to a float value, all float values smaller than the given threshold
    will be displayed as exactly 0 by repr and friends.
    [default: None] [currently: 4]
display.colheader_justify : 'left'/'right'
    Controls the justification of column headers. used by DataFrameFormatter.
    [default: right] [currently: right]
display.date_dayfirst : boolean
    When True, prints and parses dates with the day first, eg 20/01/2005
    [default: False] [currently: False]
display.date_yearfirst : boolean
    When True, prints and parses dates with the year first, eg 2005/01/20
    [default: False] [currently: False]
display.encoding : str/unicode
    Defaults to the detected encoding of the console.
    Specifies the encoding to be used for strings returned by to_string,
    these are generally strings meant to be displayed on the console.
    [default: UTF-8] [currently: UTF-8]
display.expand_frame_repr : boolean
    Whether to print out the full DataFrame repr for wide DataFrames across
    multiple lines, `max_columns` is still respected, but the output will
    wrap-around across multiple "pages" if its width exceeds `display.width`.
    [default: True] [currently: True]
display.float_format : callable
    The callable should accept a floating point number and return
    a string with the desired format of the number. This is used
    in some places like SeriesFormatter.
    See formats.format.EngFormatter for an example.
    [default: None] [currently: None]
display.html.border : int
    A ``border=value`` attribute is inserted in the ``<table>`` tag
    for the DataFrame HTML repr.
    [default: 1] [currently: 1]
display.html.table_schema : boolean
    Whether to publish a Table Schema representation for frontends
    that support it.
    (default: False)
    [default: False] [currently: False]
display.html.use_mathjax : boolean
    When True, Jupyter notebook will process table contents using MathJax,
    rendering mathematical expressions enclosed by the dollar symbol.
    (default: True)
    [default: True] [currently: True]
display.large_repr : 'truncate'/'info'
    For DataFrames exceeding max_rows/max_cols, the repr (and HTML repr) can
    show a truncated table, or switch to the view from
    df.info() (the behaviour in earlier versions of pandas).
    [default: truncate] [currently: truncate]
display.max_categories : int
    This sets the maximum number of categories pandas should output when
    printing out a `Categorical` or a Series of dtype "category".
    [default: 8] [currently: 8]
display.max_columns : int
    If max_cols is exceeded, switch to truncate view. Depending on
    `large_repr`, objects are either centrally truncated or printed as
    a summary view.

    'None' value means unlimited. Beware that printing a large number of
    columns could cause your rendering environment (the browser, etc.) to
    crash.

    In case python/IPython is running in a terminal and `large_repr`
    equals 'truncate' this can be set to 0 or None and pandas will auto-detect
    the width of the terminal and print a truncated object which fits
    the screen width. The IPython notebook, IPython qtconsole, or IDLE
    do not run in a terminal and hence it is not possible to do
    correct auto-detection and defaults to 20.
    [default: 20] [currently: 20]
display.max_colwidth : int or None
    The maximum width in characters of a column in the repr of
    a pandas data structure. When the column overflows, a "..."
    placeholder is embedded in the output. A 'None' value means unlimited.
    [default: 50] [currently: 50]
display.max_dir_items : int
    The number of items that will be added to `dir(...)`. 'None' value means
    unlimited. Because dir is cached, changing this option will not immediately
    affect already existing dataframes until a column is deleted or added.

    This is for instance used to suggest columns from a dataframe to tab
    completion.
    [default: 100] [currently: 100]
display.max_info_columns : int
    max_info_columns is used in DataFrame.info method to decide if
    per column information will be printed.
    [default: 100] [currently: 100]
display.max_info_rows : int
    df.info() will usually show null-counts for each column.
    For large frames this can be quite slow. max_info_rows and max_info_cols
    limit this null check only to frames with smaller dimensions than
    specified.
    [default: 1690785] [currently: 1690785]
display.max_rows : int
    If max_rows is exceeded, switch to truncate view. Depending on
    `large_repr`, objects are either centrally truncated or printed as
    a summary view.

    'None' value means unlimited. Beware that printing a large number of rows
    could cause your rendering environment (the browser, etc.) to crash.

    In case python/IPython is running in a terminal and `large_repr`
    equals 'truncate' this can be set to 0 and pandas will auto-detect
    the height of the terminal and print a truncated object which fits
    the screen height. The IPython notebook, IPython qtconsole, or
    IDLE do not run in a terminal and hence it is not possible to do
    correct auto-detection.
    [default: 60] [currently: 999]
display.max_seq_items : int or None
    When pretty-printing a long sequence, no more then `max_seq_items`
    will be printed. If items are omitted, they will be denoted by the
    addition of "..." to the resulting string.

    If set to None, the number of items to be printed is unlimited.
    [default: 100] [currently: 100]
display.memory_usage : bool, string or None
    This specifies if the memory usage of a DataFrame should be displayed when
    df.info() is called. Valid values True,False,'deep'
    [default: True] [currently: True]
display.min_rows : int
    The numbers of rows to show in a truncated view (when `max_rows` is
    exceeded). Ignored when `max_rows` is set to None or 0. When set to
    None, follows the value of `max_rows`.
    [default: 10] [currently: 10]
display.multi_sparse : boolean
    "sparsify" MultiIndex display (don't display repeated
    elements in outer levels within groups)
    [default: True] [currently: True]
display.notebook_repr_html : boolean
    When True, IPython notebook will use html representation for
    pandas objects (if it is available).
    [default: True] [currently: True]
display.pprint_nest_depth : int
    Controls the number of nested levels to process when pretty-printing
    [default: 3] [currently: 3]
display.precision : int
    Floating point output precision in terms of number of places after the
    decimal, for regular formatting as well as scientific notation. Similar
    to ``precision`` in :meth:`numpy.set_printoptions`.
    [default: 6] [currently: 6]
display.show_dimensions : boolean or 'truncate'
    Whether to print out dimensions at the end of DataFrame repr.
    If 'truncate' is specified, only print out the dimensions if the
    frame is truncated (e.g. not display all rows and/or columns)
    [default: truncate] [currently: truncate]
display.unicode.ambiguous_as_wide : boolean
    Whether to use the Unicode East Asian Width to calculate the display text
    width.
    Enabling this may affect to the performance (default: False)
    [default: False] [currently: False]
display.unicode.east_asian_width : boolean
    Whether to use the Unicode East Asian Width to calculate the display text
    width.
    Enabling this may affect to the performance (default: False)
    [default: False] [currently: False]
display.width : int
    Width of the display in characters. In case python/IPython is running in
    a terminal this can be set to None and pandas will correctly auto-detect
    the width.
    Note that the IPython notebook, IPython qtconsole, or IDLE do not run in a
    terminal and hence it is not possible to correctly detect the width.
    [default: 80] [currently: 80]
future.distinguish_nan_and_na Whether to treat NaN entries as distinct from pd.NA in numpy-nullable and pyarrow float dtypes. By default treats both interchangeable as missing values (NaN will be coerced to NA). See discussion in https://github.com/pandas-dev/pandas/issues/32265
    [default: False] [currently: False]
future.infer_string Whether to infer sequence of str objects as pyarrow string dtype, which will be the default in pandas 3.0 (at which point this option will be deprecated).
    [default: True] [currently: True]
future.no_silent_downcasting This option is deprecated and will be removed in a future version. It has no effect.
    [default: False] [currently: False]
    (Deprecated, use `` instead.)
future.python_scalars Whether to return Python scalars instead of NumPy or PyArrow scalars. Currently experimental, setting to True is not recommended for end users.
    [default: False] [currently: False]
io.excel.ods.reader : string
    The default Excel reader engine for 'ods' files. Available options:
    auto, odf, calamine.
    [default: auto] [currently: auto]
io.excel.ods.writer : string
    The default Excel writer engine for 'ods' files. Available options:
    auto, odf.
    [default: auto] [currently: auto]
io.excel.xls.reader : string
    The default Excel reader engine for 'xls' files. Available options:
    auto, xlrd, calamine.
    [default: auto] [currently: auto]
io.excel.xlsb.reader : string
    The default Excel reader engine for 'xlsb' files. Available options:
    auto, pyxlsb, calamine.
    [default: auto] [currently: auto]
io.excel.xlsm.reader : string
    The default Excel reader engine for 'xlsm' files. Available options:
    auto, xlrd, openpyxl, calamine.
    [default: auto] [currently: auto]
io.excel.xlsm.writer : string
    The default Excel writer engine for 'xlsm' files. Available options:
    auto, openpyxl.
    [default: auto] [currently: auto]
io.excel.xlsx.reader : string
    The default Excel reader engine for 'xlsx' files. Available options:
    auto, xlrd, openpyxl, calamine.
    [default: auto] [currently: auto]
io.excel.xlsx.writer : string
    The default Excel writer engine for 'xlsx' files. Available options:
    auto, openpyxl, xlsxwriter.
    [default: auto] [currently: auto]
io.hdf.default_format : format
    default format writing format, if None, then
    put will default to 'fixed' and append will default to 'table'
    [default: None] [currently: None]
io.hdf.dropna_table : boolean
    drop ALL nan rows when appending to a table
    [default: False] [currently: False]
io.parquet.engine : string
    The default parquet reader/writer engine. Available options:
    'auto', 'pyarrow', 'fastparquet', the default is 'auto'
    [default: auto] [currently: auto]
io.sql.engine : string
    The default sql reader/writer engine. Available options:
    'auto', 'sqlalchemy', the default is 'auto'
    [default: auto] [currently: auto]
mode.chained_assignment : string
    Raise an exception, warn, or no action if trying to use chained assignment,
    The default is warn
    [default: warn] [currently: warn]
mode.copy_on_write : bool
    Use new copy-view behaviour using Copy-on-Write. No longer used,
    pandas now always uses Copy-on-Write behavior. This option will
    be removed in pandas 4.0.
    [default: True] [currently: True]
    (Deprecated, use `` instead.)
mode.performance_warnings : boolean
    Whether to show or hide PerformanceWarnings.
    [default: True] [currently: True]
mode.sim_interactive : boolean
    Whether to simulate interactive mode for purposes of testing
    [default: False] [currently: True]
mode.string_storage : string
    The default storage for StringDtype.
    [default: auto] [currently: auto]
plotting.backend : str
    The plotting backend to use. The default value is "matplotlib", the
    backend provided with pandas. Other backends can be specified by
    providing the name of the module that implements the backend.
    [default: matplotlib] [currently: matplotlib]
plotting.matplotlib.register_converters : bool or 'auto'.
    Whether to register converters with matplotlib's units registry for
    dates, times, datetimes, and Periods. Toggling to False will remove
    the converters, restoring any converters that pandas overwrote.
    [default: auto] [currently: auto]
styler.format.decimal : str
    The character representation for the decimal separator for floats and complex.
    [default: .] [currently: .]
styler.format.escape : str, optional
    Whether to escape certain characters according to the given context; html or latex.
    [default: None] [currently: None]
styler.format.formatter : str, callable, dict, optional
    A formatter object to be used as default within ``Styler.format``.
    [default: None] [currently: None]
styler.format.na_rep : str, optional
    The string representation for values identified as missing.
    [default: None] [currently: None]
styler.format.precision : int
    The precision for floats and complex numbers.
    [default: 6] [currently: 6]
styler.format.thousands : str, optional
    The character representation for thousands separator for floats, int and complex.
    [default: None] [currently: None]
styler.html.mathjax : bool
    If False will render special CSS classes to table attributes that indicate Mathjax
    will not be used in Jupyter Notebook.
    [default: True] [currently: True]
styler.latex.environment : str
    The environment to replace ``\begin{table}``. If "longtable" is used results
    in a specific longtable environment format.
    [default: None] [currently: None]
styler.latex.hrules : bool
    Whether to add horizontal rules on top and bottom and below the headers.
    [default: False] [currently: False]
styler.latex.multicol_align : {"r", "c", "l", "naive-l", "naive-r"}
    The specifier for horizontal alignment of sparsified LaTeX multicolumns. Pipe
    decorators can also be added to non-naive values to draw vertical
    rules, e.g. "\|r" will draw a rule on the left side of right aligned merged cells.
    [default: r] [currently: r]
styler.latex.multirow_align : {"c", "t", "b"}
    The specifier for vertical alignment of sparsified LaTeX multirows.
    [default: c] [currently: c]
styler.render.encoding : str
    The encoding used for output HTML and LaTeX files.
    [default: utf-8] [currently: utf-8]
styler.render.max_columns : int, optional
    The maximum number of columns that will be rendered. May still be reduced to
    satisfy ``max_elements``, which takes precedence.
    [default: None] [currently: None]
styler.render.max_elements : int
    The maximum number of data-cell (<td>) elements that will be rendered before
    trimming will occur over columns, rows or both if needed.
    [default: 262144] [currently: 262144]
styler.render.max_rows : int, optional
    The maximum number of rows that will be rendered. May still be reduced to
    satisfy ``max_elements``, which takes precedence.
    [default: None] [currently: None]
styler.render.repr : str
    Determine which output to use in Jupyter Notebook in {"html", "latex"}.
    [default: html] [currently: html]
styler.sparse.columns : bool
    Whether to sparsify the display of hierarchical columns. Setting to False will
    display each explicit level element in a hierarchical key for each column.
    [default: True] [currently: True]
styler.sparse.index : bool
    Whether to sparsify the display of a hierarchical index. Setting to False will
    display each explicit level element in a hierarchical key for each row.
    [default: True] [currently: True]

# Getting and Setting Options

To change an option call `.set_option("option regex", new_value)`

In [37]:
# For example, this option simulates interactive mode for purposes of debugging.
pd.get_option("mode.sim_interactive")

True

In [38]:
pd.set_option("mode.sim_interactive", True)

In [39]:
pd.get_option("mode.sim_interactive")

True

To revert to the option's default value use `.reset_option()`

In [40]:
pd.get_option("display.max_rows")

999

In [41]:
pd.reset_option("display.max_rows")

In [42]:
pd.get_option("display.max_rows")

60

To execute code with a set of given values, and then restore the original values:

In [43]:
with pd.option_context("display.max_rows", 10, "display.max_columns", 5):
    print(pd.get_option("display.max_rows"))
    print(pd.get_option("display.max_columns"))

10
5

In [44]:
# When the above block of code finishes, values are restored to defaults:
print(pd.get_option("display.max_rows"))
print(pd.get_option("display.max_columns"))

60
20

# Setting Startup Options in Python/IPython Environment

# Frequently Used Options

In [51]:
pd.reset_option("all")

df = pd.DataFrame(np.random.randn(7, 2))
pd.set_option("display.max_rows", 7)
df

C:\Users\nkmil\AppData\Local\Temp\ipykernel_8700\3318954277.py:1: Pandas4Warning: 'future.no_silent_downcasting' is deprecated, please refrain from using it.
  pd.reset_option("all")
C:\Users\nkmil\AppData\Local\Temp\ipykernel_8700\3318954277.py:1: Pandas4Warning: The 'mode.copy_on_write' option is deprecated. Copy-on-Write can no longer be disabled (it is always enabled with pandas >= 3.0), and setting the option has no impact. This option will be removed in pandas 4.0.
  pd.reset_option("all")

          0         1
0 -0.104366 -0.567963
1 -0.374227 -0.586729
2  1.133614 -1.212474
3 -0.461111 -0.097722
4  0.455148 -0.867220
5 -0.906990 -0.631813
6  1.382470 -0.896386

In [52]:
pd.set_option("display.max_rows", 4)
df

           0         1
0  -0.104366 -0.567963
1  -0.374227 -0.586729
..       ...       ...
5  -0.906990 -0.631813
6   1.382470 -0.896386

[7 rows x 2 columns]

In [53]:
pd.reset_option("display.max_rows")

In [54]:
pd.set_option("display.max_rows", 8)
pd.set_option("display.min_rows", 4)

# below max_rows -> all rows shown
df = pd.DataFrame(np.random.randn(7, 2))
df

          0         1
0 -0.960855  1.313183
1 -1.130249  0.837298
2  0.406574 -0.290152
3 -0.555592 -0.643903
4  1.576269  0.702383
5  0.144484 -0.062673
6  0.366054  1.597204

In [55]:
# above max_rows -> only min_rows(4) rows shown
df = pd.DataFrame(np.random.randn(9, 2))
df

           0         1
0   1.696822 -0.175705
1   0.131896  0.248922
..       ...       ...
7  -0.207256  0.178031
8  -0.687228 -1.547238

[9 rows x 2 columns]

In [56]:
pd.reset_option("display.max_rows")
pd.reset_option("display.min_rows")

In [61]:
df = pd.DataFrame(np.random.randn(5, 15))
pd.set_option("expand_frame_repr", True)
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,1.190044,1.360931,-0.031303,-1.043862,-0.018198,0.886090,0.916603,0.167793,0.064398,-1.231671,1.345840,-0.265143,-0.682640,-0.273725,0.525076
1,-0.563551,1.205013,0.462399,-1.126229,-0.644952,0.119002,0.905207,0.302205,1.488025,-1.719568,-0.154411,0.508716,0.538122,1.592244,0.700469
2,-0.654312,0.377336,-0.205318,-0.176334,0.395769,1.567483,-0.344029,0.278290,0.993062,-0.826611,0.896248,-0.608872,0.362171,-0.782020,0.126003
3,-0.310131,-1.781284,-1.039255,0.152063,-0.715508,-0.764845,0.720144,1.125086,0.056518,0.693047,-0.351201,-1.553559,-0.610627,0.264133,0.277024
4,0.391273,-0.226954,0.927357,0.849048,0.298917,0.785921,1.430081,-0.081452,-0.212281,1.627133,-0.623102,-0.139152,-0.510830,0.098613,0.184381

In [62]:
pd.set_option("expand_frame_repr", False)
df

         0         1         2         3         4         5         6         7         8         9         10        11        12        13        14
0  1.190044  1.360931 -0.031303 -1.043862 -0.018198  0.886090  0.916603  0.167793  0.064398 -1.231671  1.345840 -0.265143 -0.682640 -0.273725  0.525076
1 -0.563551  1.205013  0.462399 -1.126229 -0.644952  0.119002  0.905207  0.302205  1.488025 -1.719568 -0.154411  0.508716  0.538122  1.592244  0.700469
2 -0.654312  0.377336 -0.205318 -0.176334  0.395769  1.567483 -0.344029  0.278290  0.993062 -0.826611  0.896248 -0.608872  0.362171 -0.782020  0.126003
3 -0.310131 -1.781284 -1.039255  0.152063 -0.715508 -0.764845  0.720144  1.125086  0.056518  0.693047 -0.351201 -1.553559 -0.610627  0.264133  0.277024
4  0.391273 -0.226954  0.927357  0.849048  0.298917  0.785921  1.430081 -0.081452 -0.212281  1.627133 -0.623102 -0.139152 -0.510830  0.098613  0.184381